#import "/template/entries.typ": create_entry
#import "/template/widgets.typ": *
#include "/template/codly.typ"

#create_entry(
  title: "Outtake",
  type: "brainstorm",
  start_date: datetime(year: 2023, month: 9, day: 23),
  attendance: "Ajibola, Ishika, Eric, Emma",
  [
    #nb_todo(date: datetime(year: 2023, month: 9, day: 23), schedule: "On Schedule")[
      + Brainstorm possible outtake mechanisms. (Everyone)
    ]

    #tablex(
      columns: (1fr, 1fr, 1fr, 1fr),
      rows: 4,
      header-rows: 1,
      align: left + top,

      cellx()[*Outtake*], 
      cellx(fill: green)[*Pros*], 
      cellx(fill: red)[*Cons*],
      cellx(fill: gray)[*Notes*],

      cellx(align: center + horizon)[#image("./Catapult outtake.svg")],
      [
        - *Angles* - Catapults can be designed to launch game elements at different angles and trajectories
        - *Consistency* - stopper allows for rapid and successive shots. 
        - *Consistent Trajectories* - Well-designed catapults can provide consistent trajectories for launched game elements. Consistency in launch angles and distances enhances the predictability of the robot's performance, allowing for more accurate scoring.
      ],
      [
        - *Risk of Overturning* - Risk of over-slipping or underslipping the drive gear #footnote([See "Slip Gear" glossary entry]).
        - *Speed* - While some catapult designs allow for rapid successive shots, achieving a high rate of fire with precision can be challenging. Reload times, tensioning mechanisms, and consistency in launching may limit the overall rapid-fire capability.
      ],
      [
        - *Calibration* - Achieving consistent and accurate shots with a catapult requires careful calibration.
        - *Safety* - Due to the potential recoil force generated by catapults, implementing safety measures is important.
      ],

      cellx(align: center + horizon)[#image("./Puncher.svg")],
      [
        - *Quick and Precise Shots* - Punchers can be designed for quick and precise shots. often using a piston or other propulsion system can release stored energy rapidly, allowing for accurate and targeted shots at scoring zones or targets.
        - *Minimal Recoil* - Compared to catapults, punchers typically generate less recoil.
        - *Rapid-Fire Capability* - Some puncher designs allow for rapid successive shots. This capability can be advantageous for maximizing the robot's cycle rate, enabling it to score multiple game elements quickly within a short time frame.
      ],
      [
        - *Limited Range* - Punchers may have a more limited range compared to other mechanisms like catapults. This limitation can affect the robot's ability to score in specific zones or targets that are situated at a distance.
        - *Impact on Robot Stability* - Depending on the design and release force, punchers can generate recoil forces that may impact the stability of the robot. Teams need to carefully consider and manage these forces to avoid stability issues, tipping, or overturning.
        - *Dependency on Release Timing* - The success of a puncher relies heavily on the timing of the release mechanism.
      ],
      [
        - Punchers rely on energy storage systems, such as rubber bands or springs, to store potential energy that is later released to launch game elements.
        - Punchers generate recoil forces upon release, which can impact the stability of the robot.
      ],
      
      cellx(align: center + horizon)[#image("./flywheel outtake.svg")],
      [
        - *High Rate of Fire* - Flywheel mechanisms can and achieve a high rate of fire, allowing for rapid successive actions.
        - *Precise Control of Speed* - Teams can have precise control over the speed of a flywheel. This control is essential for fine-tuning the performance of mechanisms and ensuring optimal results in terms of accuracy and consistency.
        - *Size and Weight Considerations* - Depending on the design, flywheel mechanisms can be compact and lightweight


      ],
      [
        - *Energy Loss Over Time* - Flywheels experience energy loss over time due to factors such as friction and air resistance. This loss can affect the consistency of performance
        - *Limited to Rotary Applications* - Flywheels are best suited for rotary applications and may have limitations in their adaptability to certain linear or more complex mechanisms.
        - *Start Up* - flywheels may require an initial energy input to reach the desired operating speed
      ],
      [
        - Achieving precise control over the speed of a flywheel is crucial. Calibration involves adjusting parameters such as motor power, gear ratios, and flywheel size to ensure the desired speed and responsiveness.
        - Flywheels may encounter challenges with dynamic loads. Should not be a problem during this season.
      ],
    )
  ]
)