#let entry-list-1 = (
 (
 title: "Pre-Reveal Reflection",
 type: "identify",
 start_date: datetime(year: 2023, month: 3, day: 17),
 end_date: datetime(year: 2023, month: 3, day: 17),
 attendance: "Ajibola, Emma, Von, Eric",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 1,
 ),
 (
 title: "Reveal Video Thoughts",
 type: "identify",
 start_date: datetime(year: 2023, month: 4, day: 29),
 end_date: datetime(year: 2023, month: 4, day: 29),
 attendance: "Ajibola, Emma, Von, Eric",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 3,
 ),
 (
 title: "Game Challenge - Analysis",
 type: "identify",
 start_date: datetime(year: 2023, month: 4, day: 30),
 end_date: datetime(year: 2023, month: 4, day: 30),
 attendance: "Ajibola, Emma, Von, Eric",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 4,
 ),
 (
 title: "Over Under Season Gantt Chart",
 type: "management",
 start_date: datetime(year: 2023, month: 7, day: 14),
 end_date: datetime(year: 2023, month: 7, day: 14),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 10,
 ),
 (
 title: "July Gantt Chart",
 type: "management",
 start_date: datetime(year: 2023, month: 7, day: 14),
 end_date: datetime(year: 2023, month: 7, day: 14),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 11,
 ),
 (
 title: "Game Challenge - Design Strategies",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 7, day: 14),
 end_date: datetime(year: 2023, month: 7, day: 14),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ishika",
 witnessed: "Ajibola",
 body: 12,
 ),
 (
 title: "Game Challenge - Design Strategies",
 type: "select",
 start_date: datetime(year: 2023, month: 7, day: 14),
 end_date: datetime(year: 2023, month: 7, day: 14),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 14,
 ),
 (
 title: "Drivetrain #1 - Identify Design Goals and Constraints",
 type: "identify",
 start_date: datetime(year: 2023, month: 7, day: 15),
 end_date: datetime(year: 2023, month: 7, day: 15),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 16,
 ),
 (
 title: "Drivetrain #1",
 type: "understand",
 start_date: datetime(year: 2023, month: 7, day: 15),
 end_date: datetime(year: 2023, month: 7, day: 15),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 17,
 ),
 (
 title: "Drivetrain #1 - Drive Configurations",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 7, day: 21),
 end_date: datetime(year: 2023, month: 7, day: 21),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 19,
 ),
 (
 title: "Drivetrain #1 - Drive Configurations",
 type: "select",
 start_date: datetime(year: 2023, month: 7, day: 21),
 end_date: datetime(year: 2023, month: 7, day: 21),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Eric",
 witnessed: "Ishika",
 body: 21,
 ),
 (
 title: "Drivetrain #1 - Wheel Types",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 7, day: 22),
 end_date: datetime(year: 2023, month: 7, day: 22),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 23,
 ),
 (
 title: "Drivetrain #1 - Wheel Types",
 type: "select",
 start_date: datetime(year: 2023, month: 7, day: 22),
 end_date: datetime(year: 2023, month: 7, day: 22),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ishika",
 witnessed: "Eric",
 body: 27,
 ),
 (
 title: "Drivetrain #1 - Gear Ratio",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 7, day: 28),
 end_date: datetime(year: 2023, month: 7, day: 28),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 29,
 ),
 (
 title: "Drivetrain #1 - Gear Ratio",
 type: "select",
 start_date: datetime(year: 2023, month: 7, day: 29),
 end_date: datetime(year: 2023, month: 7, day: 29),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 31,
 ),
 (
 title: "August Gantt Chart",
 type: "management",
 start_date: datetime(year: 2023, month: 8, day: 5),
 end_date: datetime(year: 2023, month: 8, day: 5),
 attendance: "Ajibola, Ishika, Eric, Makhi",
 designed: "Ajibola",
 witnessed: "Makhi",
 body: 39,
 ),
 (
 title: "Drivetrain #1",
 type: "build",
 start_date: datetime(year: 2023, month: 8, day: 5),
 end_date: datetime(year: 2023, month: 8, day: 26),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ishika",
 witnessed: "Rory",
 body: 40,
 ),
 (
 title: "September Gantt Chart",
 type: "management",
 start_date: datetime(year: 2023, month: 9, day: 8),
 end_date: datetime(year: 2023, month: 9, day: 8),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Eric",
 witnessed: "Rory",
 body: 45,
 ),
 (
 title: "Drivetrain #1",
 type: "build",
 start_date: datetime(year: 2023, month: 9, day: 8),
 end_date: datetime(year: 2023, month: 9, day: 15),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ishika",
 witnessed: "Ajibola",
 body: 46,
 ),
 (
 title: "Drivetrain #1 - Driver Control",
 type: "program",
 start_date: datetime(year: 2023, month: 9, day: 15),
 end_date: datetime(year: 2023, month: 9, day: 15),
 attendance: "Ajibola, Ishika, Eric, Rory",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 48,
 ),
 (
 title: "Drivetrain #1",
 type: "test",
 start_date: datetime(year: 2023, month: 9, day: 15),
 end_date: datetime(year: 2023, month: 9, day: 15),
 attendance: "Ajibola, Ishika, Makhi, Eric, Rory",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 55,
 ),
 (
 title: "Outtake - Identify Design Goals and Constraints",
 type: "identify",
 start_date: datetime(year: 2023, month: 9, day: 16),
 end_date: datetime(year: 2023, month: 9, day: 16),
 attendance: "Ajibola, Ishika, Eric, Rory",
 designed: "Rory",
 witnessed: "Eric",
 body: 58,
 ),
 (
 title: "Wings #1 - Identify Design Goals and Constraints",
 type: "identify",
 start_date: datetime(year: 2023, month: 9, day: 22),
 end_date: datetime(year: 2023, month: 9, day: 22),
 attendance: "Ajibola, Ishika, Eric, Rory",
 designed: "Rory",
 witnessed: "Ajibola",
 body: 59,
 ),
 (
 title: "Wings #1",
 type: "understand",
 start_date: datetime(year: 2023, month: 9, day: 22),
 end_date: datetime(year: 2023, month: 9, day: 22),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Makhi",
 witnessed: "Ajibola",
 body: 60,
 ),
 (
 title: "Outtake",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 9, day: 23),
 end_date: datetime(year: 2023, month: 9, day: 23),
 attendance: "Ajibola, Ishika, Makhi, Eric, Rory",
 designed: "Rory",
 witnessed: "Makhi",
 body: 62,
 ),
 (
 title: "Outtake #1",
 type: "select",
 start_date: datetime(year: 2023, month: 9, day: 23),
 end_date: datetime(year: 2023, month: 9, day: 23),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 65,
 ),
 (
 title: "Catapult #1",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 9, day: 23),
 end_date: datetime(year: 2023, month: 9, day: 23),
 attendance: "Ajibola, Ishika, Eric, Makhi",
 designed: "Ajibola",
 witnessed: "Makhi",
 body: 67,
 ),
 (
 title: "Catapult #1",
 type: "select",
 start_date: datetime(year: 2023, month: 9, day: 23),
 end_date: datetime(year: 2023, month: 9, day: 23),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 69,
 ),
 (
 title: "Wings #1",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 9, day: 23),
 end_date: datetime(year: 2023, month: 9, day: 23),
 attendance: "Ajibola, Ishika, Eric, Makhi",
 designed: "Ajibola",
 witnessed: "Makhi",
 body: 78,
 ),
 (
 title: "Wings #1",
 type: "select",
 start_date: datetime(year: 2023, month: 9, day: 23),
 end_date: datetime(year: 2023, month: 9, day: 23),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Makhi",
 body: 80,
 ),
 (
 title: "Kanban Board",
 type: "management",
 start_date: datetime(year: 2023, month: 9, day: 30),
 end_date: datetime(year: 2023, month: 9, day: 30),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi,",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 85,
 ),
 (
 title: "Catapult #1 - Low Catapult",
 type: "build",
 start_date: datetime(year: 2023, month: 9, day: 30),
 end_date: datetime(year: 2023, month: 10, day: 7),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Rory",
 body: 88,
 ),
 (
 title: "Wings #1",
 type: "build",
 start_date: datetime(year: 2023, month: 9, day: 30),
 end_date: datetime(year: 2023, month: 10, day: 6),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Rory",
 body: 91,
 ),
 (
 title: "October Gantt Chart",
 type: "management",
 start_date: datetime(year: 2023, month: 10, day: 7),
 end_date: datetime(year: 2023, month: 10, day: 7),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 93,
 ),
 (
 title: "Catapult #1 - Low Catapult",
 type: "program",
 start_date: datetime(year: 2023, month: 10, day: 7),
 end_date: datetime(year: 2023, month: 10, day: 7),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ishika",
 witnessed: "Ajibola",
 body: 94,
 ),
 (
 title: "Catapult #1 - Low Catapult",
 type: "test",
 start_date: datetime(year: 2023, month: 10, day: 7),
 end_date: datetime(year: 2023, month: 10, day: 7),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Makhi",
 body: 96,
 ),
 (
 title: "Wings #1",
 type: "program",
 start_date: datetime(year: 2023, month: 10, day: 13),
 end_date: datetime(year: 2023, month: 10, day: 13),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 98,
 ),
 (
 title: "Wings #1",
 type: "test",
 start_date: datetime(year: 2023, month: 10, day: 13),
 end_date: datetime(year: 2023, month: 10, day: 13),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Rory",
 body: 100,
 ),
 (
 title: "Intake #1 - Identify Design Goals and Constraints",
 type: "identify",
 start_date: datetime(year: 2023, month: 10, day: 14),
 end_date: datetime(year: 2023, month: 10, day: 14),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 102,
 ),
 (
 title: "Intake #1",
 type: "understand",
 start_date: datetime(year: 2023, month: 10, day: 14),
 end_date: datetime(year: 2023, month: 10, day: 14),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 104,
 ),
 (
 title: "Intake #1",
 type: "brainstorm",
 start_date: datetime(year: 2023, month: 10, day: 14),
 end_date: datetime(year: 2023, month: 10, day: 14),
 attendance: "Ajibola, Ishika, Eric, Makhi",
 designed: "Ajibola",
 witnessed: "Makhi",
 body: 107,
 ),
 (
 title: "Intake #1",
 type: "select",
 start_date: datetime(year: 2023, month: 10, day: 14),
 end_date: datetime(year: 2023, month: 10, day: 14),
 attendance: "Ajibola, Ishika, Eric, Emma",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 110,
 ),
 (
 title: "Area 53 Scrimmage",
 type: "competition",
 start_date: datetime(year: 2023, month: 10, day: 21),
 end_date: datetime(year: 2023, month: 10, day: 21),
 attendance: "Ajibola, Ishika, Makhi, Eric, Rory",
 designed: "Ajibola",
 witnessed: "Eric",
 body: 115,
 ),
 (
 title: "Intake #1",
 type: "build",
 start_date: datetime(year: 2023, month: 10, day: 27),
 end_date: datetime(year: 2023, month: 10, day: 28),
 attendance: "Ajibola, Ishika, Eric, Rory, Makhi",
 designed: "Rory",
 witnessed: "Eric",
 body: 120,
 ),
 (
 title: "November Gantt Chart",
 type: "management",
 start_date: datetime(year: 2023, month: 11, day: 3),
 end_date: datetime(year: 2023, month: 11, day: 3),
 attendance: "",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 122,
 ),
 (
 title: "Intake #1",
 type: "program",
 start_date: datetime(year: 2023, month: 11, day: 3),
 end_date: datetime(year: 2023, month: 11, day: 3),
 attendance: "Ajibola, Ishika, Rory, Makhi",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 123,
 ),
 (
 title: "Intake #1",
 type: "test",
 start_date: datetime(year: 2023, month: 11, day: 3),
 end_date: datetime(year: 2023, month: 11, day: 3),
 attendance: "Ajibola, Ishika, Makhi, Eric, Rory",
 designed: "Rory",
 witnessed: "Ajibola",
 body: 125,
 ),
 (
 title: "Dulaney Royal Rumble",
 type: "competition",
 start_date: datetime(year: 2023, month: 11, day: 4),
 end_date: datetime(year: 2023, month: 11, day: 4),
 attendance: "Ajibola, Ishika, Makhi, Rory",
 designed: "Ajibola",
 witnessed: "Ishika",
 body: 127,
 ),
)

#let full-entry-list = entry-list-1