name: Build Typst Document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Typst
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: typst-cli
          git: https://github.com/typst/typst
          branch: main

      - name: Compile Notebook
        run: typst compile main.typ --font-path ./assets/fonts/
          
      - name: Upload PDF File
        uses: actions/upload-artifact@v3.1.3
        with:
          name: notebook
          path: main.pdf
      
      - name: Upload to Discord
        uses: ToppleTheNun/discord-scm-action@v1.0.2
        with:
          discordWebhookId: ${{ secrets.DISCORD_WEBHOOK_ID }}
          discordWebhookToken: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          artifacts: main.pdf